# Ci pipeline to build docker images
# and push to gitlab docker registry
# auto deploy as well

stages:
  - build

docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo -n $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - ssh -t -t nodejstest@ibcpods.com "docker pull '$CI_REGISTRY_IMAGE' && docker rm -f sgri-web && docker run -d -p 50052:80 --name sgri-web -e SERVER_URL=http://ibcpods.com:50053 -e HASURA_URL="http://ibcpods.com:50083/api/rest" -e SGRI_API="/api" -e HASURA_SECRET="ItPnPIWl9ZDP3YzkGrmOkocoqZs4FE5w" --restart unless-stopped '$CI_REGISTRY_IMAGE' && exit"
  only:
    - ibcpods
